name: Deploy Databricks bundle

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions: 
  contents: read

jobs:  
  deploy-dev:
    name: Deploy to Dev
    if: github.event.inputs.target_env == 'dev'
    runs-on: ubuntu-latest
    env:      
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}

      # variables
      TF_VAR_workspace_url: ${{ secrets.DATABRICKS_HOST_DEV }}
      TF_VAR_zerobus_workspace_id: ${{ secrets.ZEROBUS_WORKSPACE_ID_DEV }}
      TF_VAR_catalog_name: ${{ secrets.CATALOG_NAME_DEV }}
      TF_VAR_csv_api_app_name: ${{ secrets.CSV_API_APP_NAME_DEV }}
      TF_VAR_zerobus_region: ${{ secrets.ZEROBUS_REGION_DEV }}

    steps:
      - uses: actions/checkout@v7
      - uses: databricks/setup-cli@v1.20.0

      - name: Validate bundle (Dev)
        run: databricks bundle validate --target dev

      - name: Deploy bundle (Dev)
        run: databricks bundle deploy --target dev

  
  deploy-prod:
    name: Deploy to Prod
    if: github.event.inputs.target_env == 'prod'
    runs-on: ubuntu-latest
    environment: prod
    env:      
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}

      #variables
      TF_VAR_workspace_url: ${{ secrets.DATABRICKS_HOST_PROD }}
      TF_VAR_zerobus_workspace_id: ${{ secrets.ZEROBUS_WORKSPACE_ID_PROD }}
      TF_VAR_catalog_name: ${{ secrets.CATALOG_NAME_PROD }}
      TF_VAR_csv_api_app_name: ${{ secrets.CSV_API_APP_NAME_PROD }}
      TF_VAR_zerobus_region: ${{ secrets.ZEROBUS_REGION_PROD }}

    steps:
      - uses: actions/checkout@v7
      - uses: databricks/setup-cli@v1.20.0

      - name: Validate bundle (Prod)
        run: databricks bundle validate --target prod

      - name: Deploy bundle (Prod)
        run: databricks bundle deploy --target prod
